---
driver:
  name: vagrant
  customize:
    cpus: 1
    memory: 2048
    
provisioner:
  name: chef_solo
  require_chef_omnibus: 12.21.1


platforms:
 - name: windows-2012-r2
   driver_config:
     box_url: E:\\artifactory\\windows2012r2min-hyperv.box
     provider: hyperv
     memory: 2048
     cpus: 1
     network:
       - ["private_network",{bridge: "internal_switch"}]

suites:
  - name: default
    run_list:
      - recipe[windows_ad::default]
    attributes:
  - name: forest
    run_list:
      - recipe[windows_ad::default]
      - recipe[windows_ad::contoso]
    attributes:
